version: '3'
services:
  credit-service-client:
    container_name: credit-calculator-client-container
    image: "${CONTAINER_REGISTRY_URL}/${CONTAINER_REGISTRY_USERNAME}/credit-calculator-client:latest"
    environment:
      - "CLIENT_PORT=${CLIENT_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"