name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    env:
      CLIENT_PORT: ${{ vars.CLIENT_PORT }}
    steps:
      - name: Checkout v2
        uses: actions@checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

        